// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGGeOvf5D888EIJmAEPCP26vm33PA585E',
    appId: '1:641197976047:web:96e959412bad8baa942e1a',
    messagingSenderId: '641197976047',
    projectId: 'ecommerce-task-test',
    authDomain: 'ecommerce-task-test.firebaseapp.com',
    storageBucket: 'ecommerce-task-test.firebasestorage.app',
    measurementId: 'G-VKPT6DDJM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIRAFXpnCEBreAh8ZKW2_7-EVKtJPPVQ',
    appId: '1:641197976047:android:14533d5a849bf07a942e1a',
    messagingSenderId: '641197976047',
    projectId: 'ecommerce-task-test',
    storageBucket: 'ecommerce-task-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHWt482qV3Z9kKwvKJAJbg6e5zTiPIqSU',
    appId: '1:641197976047:ios:1734ea27efdca365942e1a',
    messagingSenderId: '641197976047',
    projectId: 'ecommerce-task-test',
    storageBucket: 'ecommerce-task-test.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceTaskTest',
  );

}